title: Dajana Herichova
description: > # this means to ignore newlines until "baseurl:"
  Clojure and ClojureScript developer"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://herichovadajana.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "https://twitter.com/herichovadajana" #if your site has a twitter account, enter it here

# Author Settings
author: Dajana Herichova # add your name
author-img: photo.JPG # add your photo
about-author: Clojure and ClojureScript developer # add description
social-twitter: herichovadajana # add your Twitter handle
social-instagram: dajanka.3d # add your ig handle
social-github: herichovadajana # github handle
social-linkedin: herichovadajana # add your Linkedin handle
social-email: dajana.herichova@gmail.com # add your Email address

# Talkyard

talkyard_server_url: https://comments-for-herichovadajana-github-io.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js


# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
